<?php
namespace MultiMaps;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-20 at 09:41:36.
 */
class MapServicesTest extends \MediaWikiTestCase {

	/**
	 *
	 */
	public function testGetServiceInstance() {
		global $egMultiMaps_MapServices;

		$defaultService = MapServices::getServiceInstance();
		$firstService = MapServices::getServiceInstance( $egMultiMaps_MapServices[0] );
		$defaultServiceWARNING = MapServices::getServiceInstance( 'fictive' );
		$this->assertTrue( $defaultService instanceof BaseMapService );
		$this->assertTrue( $firstService instanceof BaseMapService );
		$this->assertTrue( $defaultServiceWARNING instanceof BaseMapService );
		$this->assertEquals( $defaultService, $firstService );
		$this->assertEquals( $defaultService->classname, $defaultServiceWARNING->classname );
		$this->assertEquals( $defaultService->getErrorMessages(), [] );
		$this->assertNotEquals( $defaultServiceWARNING->getErrorMessages(), [] );
	}

	public function testExceptionOnGetServiceInstance() {
		global $egMultiMaps_MapServices;

		$MapServices = $egMultiMaps_MapServices;
		$egMultiMaps_MapServices = [];

		$this->assertTrue( MapServices::getServiceInstance() instanceof Leaflet );

		$egMultiMaps_MapServices = $MapServices;
	}

	public function testErrorsOnGetServiceInstance() {
		global $egMultiMaps_MapServices;

		$MapServices = $egMultiMaps_MapServices;
		$egMultiMaps_MapServices = [ 'fictive', 'Marker' ];

		$this->assertTrue( MapServices::getServiceInstance( 'fictive' ) instanceof Leaflet );
		$this->assertTrue( MapServices::getServiceInstance( 'Marker' ) instanceof Leaflet );
		$this->assertTrue( MapServices::getServiceInstance( 'fictivefictive' ) instanceof Leaflet );

		$egMultiMaps_MapServices = $MapServices;
	}

}
